### ISSUE TITLE
can the 'canmelee' and 'melee' apis take a unit instead of a direction?

### ISSUE THREAD

**Issue by raph714** [bovard/raid#36]
it took me a long time to figure out how to change a unit into a direction to ask if i could attack it, i can see that being frustrating.

**Comment by raph714** [comment]
in fact, i don't think i can change a unitInfo into a direction from the user based on the published api.

**Comment by bovard** [comment]
ourLocation.directionTo(unitinfo.location)

**Comment by bovard** [comment]
but yeah, could consider changing that to unit

**Comment by cdubz** [comment]
I actually stumbled on this at first as well, but I don't think we should change anything here. @bovard are you suggest changing to `MapLocation.directionTo(unit)`? Or `UnitController.canMeleeAttack(unit)` and `meleeAtack(unit)`? If anything I could see changing those two to use `MapLocation` instead of `Direction`, but I dont think `Unit` makes sense in any case.

**Comment by raph714** [comment]
I think it might be cool as `MapLocation` because all the other attack methods take them, it would make it a little easier and consistent.

**Comment by cdubz** [comment]
Agreed. See #50.
